export const ORGANIZATION_MEMBER_PAGE_SIZE = 10;

export const ORGANIZATION_INVITATION_PAGE_SIZE = 10;

export const INVITATION_RESEND_COOLDOWN_SECONDS = 60;

export const INVITATION_LINK_EXPIRY_MINUTES = 15;